version: '3.8'

# PostgreSQL Primary-Standby Replication Setup
# This Docker Compose file creates a PostgreSQL streaming replication cluster
# with one primary and one standby instance.

services:
  # Primary PostgreSQL Instance
  postgres-primary:
    image: postgres:16-alpine
    container_name: postgres-primary
    hostname: postgres-primary
    environment:
      # Basic PostgreSQL configuration
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_pass
      POSTGRES_DB: production

      # Replication user credentials
      POSTGRES_REPLICATION_USER: replicator
      POSTGRES_REPLICATION_PASSWORD: repl_password

    volumes:
      # Data persistence
      - primary-data:/var/lib/postgresql/data

      # Shared WAL archive directory
      - wal-archive:/var/lib/postgresql/wal_archive

      # Custom initialization script
      - ./init-primary.sh:/docker-entrypoint-initdb.d/init-primary.sh:ro

    ports:
      - "5432:5432"

    networks:
      - postgres-cluster

    command:
      - postgres
      # Enable WAL archiving for PITR (Point-In-Time Recovery)
      - -c
      - wal_level=replica
      - -c
      - max_wal_senders=10
      - -c
      - max_replication_slots=10
      - -c
      - hot_standby=on
      - -c
      - archive_mode=on
      - -c
      - archive_command=test ! -f /var/lib/postgresql/wal_archive/%f && cp %p /var/lib/postgresql/wal_archive/%f
      - -c
      - archive_timeout=60

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Standby PostgreSQL Instance (Replica)
  postgres-standby:
    image: postgres:16-alpine
    container_name: postgres-standby
    hostname: postgres-standby
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_pass

      # Replication connection settings
      PRIMARY_HOST: postgres-primary
      PRIMARY_PORT: 5432
      REPLICATION_USER: replicator
      REPLICATION_PASSWORD: repl_password

    volumes:
      # Separate data volume for standby
      - standby-data:/var/lib/postgresql/data

      # Shared WAL archive (read-only access)
      - wal-archive:/var/lib/postgresql/wal_archive:ro

      # Initialization script for standby setup
      - ./init-standby.sh:/docker-entrypoint-initdb.d/init-standby.sh:ro

    ports:
      - "5433:5432"

    networks:
      - postgres-cluster

    depends_on:
      postgres-primary:
        condition: service_healthy

    command:
      - postgres
      - -c
      - hot_standby=on
      - -c
      - max_standby_streaming_delay=30s
      - -c
      - wal_receiver_status_interval=10s

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

# Named volumes for data persistence
volumes:
  primary-data:
    driver: local
  standby-data:
    driver: local
  wal-archive:
    driver: local

# Network for cluster communication
networks:
  postgres-cluster:
    driver: bridge
